---
- hosts: all
  vars_files:
  - vars/root.yml
  tasks:
  - name: install packages
    dnf: state=present name={{ item }}
    with_items: "{{ fedora_packages }}"

  - name: create docker group
    group:
      name: docker
      state: present

  - name: add user to docker group
    user:
      name: "{{ ansible_ssh_user }}"
      groups: docker
      append: yes

  - name: permanently enable docker service
    service:
      name: docker
      enabled: yes
