---
- hosts: all
  tasks:
  - name: install packages
    dnf: state=present name={{ item }}
    with_items:
    # tools
    - python3
    - python3-ipython
    - pass
    - task
    - fish
    - vim
    - htop
    - gnome-tweak-tool
    - pandoc
    - youtube-dl
    - git
    - xsel
    - colordiff
    - mc
    - meld
    # libs
    - python-pygments
    - python3-pygments
    - python3-sphinx
    - python3-beautifulsoup4
    # apps
    - pidgin-otr
    - pidgin
    - gnucash
    - thunderbird
    - deluge
    - zeal
    - gimp
  - name: change users default shell
    user: name={{ ansible_ssh_user }} shell=/usr/bin/fish
    become: yes
