---
- hosts: all
  tasks:
  - name: "set variables"
    set_fact:
      home: "{{ ansible_env.HOME }}"

  - name: copy fish functions
    copy: src=fish/functions/ dest={{ home }}/.config/fish/functions

  - name: copy fish completions
    copy: src=fish/completions/ dest={{ home }}/.config/fish/completions

  - name: initialize the g function completion
    script: /usr/bin/fish -c "g"

  - name: install user abbreviations
    script: /usr/bin/fish fish/abbreviations.fish
