---
- hosts: all
  vars_files:
  - vars/user.yml
  tasks:
  - name: "set variables"
    set_fact:
      home: "{{ ansible_env.HOME }}"

  - name: copy fish functions
    copy: src=fish/functions/ dest={{ home }}/.config/fish/functions

  - name: copy fish completions
    copy: src=fish/completions/ dest={{ home }}/.config/fish/completions

  - name: copy fish config
    copy: src=fish/config.fish dest={{ home }}/.config/fish/config.fish

  - name: create the links directory for 'g' function
    file: state=directory path={{ home }}/.g

  - name: install fish shell abbreviations
    fish_abbr: name={{ item.name }} value={{ item.value }}
    with_items: "{{ fish_abbreviations }}"

  - name: setup git status to be short globally
    git_config: name=status.short scope=global value=true

  - name: set vim as default editor for git commit
    git_config: name=core.editor scope=global value=vim

  - name: configure git to use the global gitignore file
    git_config: name=core.excludesfile scope=global value="{{ home }}/.gitignore"

  - name: set meld as the default merge tool
    git_config: name=merge.tool scope=global value=meld

  - name: ensure .sublime-project and .sublime-workspace files are ignored globally by git
    lineinfile:
      dest: ~/.gitignore
      line: "{{ item }}"
      create: yes
    with_items:
      - "*.sublime-project"
      - "*.sublime-workspace"

  - name: set sublime tab_size for python
    json_edit:
      file: "{{ home }}/.config/sublime-text-3/Packages/User/Python.sublime-settings"
      name: tab_size
      value: 4
      type: int

  - name: set sublime rulers for python to 79 chars
    json_edit:
      file: "{{ home }}/.config/sublime-text-3/Packages/User/Python.sublime-settings"
      name: rulers
      value: "[79]"
      type: json

  - name: set sublime translate_tabs_to_spaces for python to true
    json_edit:
      file: "{{ home }}/.config/sublime-text-3/Packages/User/Python.sublime-settings"
      name: translate_tabs_to_spaces
      value: true
      type: bool

# set gnome shortcuts
  - name: copy the gnome shortcuts dump
    copy: src=files/shortcuts.dconf dest=/tmp/shortcuts.dconf

  - name: load the dump by dconf
    shell: dconf load /org/gnome/settings-daemon/plugins/media-keys/ < /tmp/shortcuts.dconf

  - name: copy the gnome minimize dump
    copy: src=files/minimize.dconf dest=/tmp/minimize.dconf

  - name: enable the minimize button on gnome
    shell: dconf load / < /tmp/minimize.dconf
