---
- hosts: all
  tasks:
  - name: "set variables"
    set_fact:
      home: "{{ ansible_env.HOME }}"

  - name: copy fish functions
    copy: src=fish/functions/ dest={{ home }}/.config/fish/functions

  - name: copy fish completions
    copy: src=fish/completions/ dest={{ home }}/.config/fish/completions

  - name: copy fish config
    copy: src=fish/config.fish dest={{ home }}/.config/fish/config.fish

  - name: initialize the g function completion
    script: /usr/bin/fish -c "g"

  - name: install user abbreviations
    script: /usr/bin/fish fish/abbreviations.fish

  - name: setup git status to be short globally
    git_config: name=status.short scope=global value=true

  - name: set vim as default editor for git commit
    git_config: name=core.editor scope=global value=vim

  - name: configure the global gitignore file
    git_config: name=core.excludesfile scope=global value="~/.gitignore"
