---
- name: copy the xbindkeys config
  copy: src=roles/gnome/files/.xbindkeysrc dest={{ ansible_env.HOME }}/.xbindkeysrc

- name: enable xbindkeys permanently
  copy: src=roles/gnome/files/xbindkeys.desktop dest={{ ansible_env.HOME }}/.config/autostart/

- name: Add minimize button to windows
  gsetting:
    schema: "org.gnome.desktop.wm.preferences"
    key: "button-layout"
    value: "'appmenu:minimize,close'"

- name: Show date in top bar
  gsetting:
    schema: "org.gnome.desktop.interface"
    key: clock-show-date
    value: true
