---
- name: copy the xbindkeys config
  copy: src=roles/gnome/files/.xbindkeysrc dest={{ ansible_env.HOME }}/.xbindkeysrc

- name: Add minimize button to windows
  gsetting:
    schema: "org.gnome.desktop.wm.preferences"
    key: "button-layout"
    value: "'appmenu:minimize,close'"
