---
- name: Add spotify repo
  yum_repository:
    name: fedora-spotify
    description: negativo17 - Spotify
    baseurl: https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: yes

- name: install spotify
  dnf:
    name: spotify
    state: present

# [fedora-spotify]
# name=negativo17 - Spotify
# baseurl=https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
# enabled=1
# skip_if_unavailable=1
# gpgkey=https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
# gpgcheck=1
# enabled_metadata=1
# metadata_expire=6h
# type=rpm-md
# repo_gpgcheck=0