---
- name: Add spotify repo
  yum_repository:
    name: fedora-spotify
    description: negativo17 - Spotify
    baseurl: https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: yes

- name: install spotify
  dnf:
    name: spotify
    state: present

- name: Install the rpmfusion repo packages
  dnf: name={{ item }}
       state=present
  with_items:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm

- name: Install steam
  dnf:
    name: steam
    state: present

- name: Install ffmpeg and gstreamer-plugins-*
  dnf: name={{ item }}
       steam=present
  with_items:
    - ffmpeg
    - gstreamer-plugins-good
    - gstreamer-plugins-bad
    - gstreamer-plugins-ugly
