---
- name: install CLI packages
  dnf: state=present name={{ item }}
  with_items: "{{ cli_packages }}"
  become: true
  tags:
  - root
  - cli

- name: install GUI packages
  dnf: state=present name={{ item }}
  with_items: "{{ gui_packages }}"
  become: true
  tags:
  - root
  - gui
