---
- name: install CLI packages
  dnf: state=present name={{ item }}
  with_items: "{{ cli_packages }}"
  tags:
  - root
  - cli

- name: install GUI packages
  dnf: state=present name={{ item }}
  with_items: "{{ gui_packages }}"
  tags:
  - root
  - gui

- name: mount /var/log as tmpfs
  mount:
    path: /var/log
    src: none
    fstype: tmpfs
    state: mounted
    opts: size=10%

- name: mount /var/log as tmpfs
  mount:
    path: "{{ ansible_env.HOME }}/.cache"
    src: none
    fstype: tmpfs
    state: mounted
    opts: size=4G,user,noauto
